version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    restart: always
    env_file: ./.env
    container_name: postgres_habit_tracker_docker
    user: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=habit_tracker_docker
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    tty: true
    command: >
      bash -c "python manage.py makemigrations 
      && python manage.py migrate
      && python manage.py loaddata data_users.json
      && python manage.py loaddata data_habits.json
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      postgres:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - postgres
      - api

#  celery_beat:
#    build: .
#    restart: always
#    tty: true
#    command: celery -A config beat -l INFO -S django
#    depends_on:
#      - redis
#      - postgres
#      - api


volumes:
  postgres_data:

