# Generated by Django 4.2.4 on 2023-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='выполняемое действие'),
        ),
    ]
