# Generated by Django 4.2.4 on 2023-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=150, verbose_name='выполняемое действие'),
        ),
    ]
