# Generated by Django 4.2.4 on 2023-09-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['id'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
    ]
